language: java
jdk:
- oraclejdk8
env:
  global:
  - DB_URL=jdbc:postgresql://localhost:5432/browser_calls
  - DB_USERNAME=postgres
before_script:
- psql -c 'create database browser_calls;' -U postgres
- ./gradlew flywayMigrate
